<template>
  <div>
    <p>分类</p>
    <div class="wrapper">
      <ul class="content">
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
        <li>ha</li>
      </ul>
    </div>
  </div>
</template>
<script>
import Bscroll from "better-scroll";
export default {
  name: "category",
  data() {
    return {
      scroll: null,
    };
  },
  // xiaobug---组件创建完后。但是目前还未挂在模板
  // created() {
  //   this.scroll = new Bscroll(document.querySelector(".wrapper"), {});
  // },
  mounted() {
    this.scroll = new Bscroll(document.querySelector(".wrapper"), {});
  },
};
</script>

<style>
h2 {
  color: red;
}
.wrapper {
  height: 400px;
  overflow: hidden;
  /* overflow-y: scroll; */
}
</style>
